#!/bin/sh

#############
# nginx
#############

# define folder for additional configurations
if [ ! -d "/etc/nginx/default.d" ]; then
  mkdir -p -m 755 /etc/nginx/default.d
fi

cat >/etc/nginx/http.d/default.conf <<EOF
server {
    root ${APP_HOME};
    index index.php index.html index.htm;

    client_max_body_size  100M;
    client_body_temp_path  /tmp;

    access_log  /dev/stdout  main;

    location = /favicon.ico { log_not_found off; access_log off; }
    location = /robot.txt { log_not_found off; access_log off; }

    location ~ \.js\.gzip$ {
        add_header Content-Encoding gzip;
        gzip off;
        types { text/javascript gzip; }
    }
    location ~ \.css\.gzip$ {
        add_header Content-Encoding gzip;
        gzip off;
        types { text/css gzip; }
    }

    if (!-e \$request_filename) {
        rewrite ^/(.+)\.(\d+)\.(php|js|css|png|jpg|gif|gzip)$ /\$1.\$3 last;
    }

    location ~* composer\.(?:json|lock) {
        deny all;
    }

    location ~* flexform[^.]*\.xml {
        deny all;
    }

    location ~* locallang[^.]*\.(?:xml|xlf)$ {
        deny all;
    }

    location ~* ext_conf_template\.txt|ext_typoscript_constants\.txt|ext_typoscript_setup\.txt {
        deny all;
    }

    location ~* /.*\.(?:bak|co?nf|cfg|ya?ml|ts|typoscript|tsconfig|dist|fla|in[ci]|log|sh|sql|sqlite)$ {
        deny all;
    }

    location ~ _(?:recycler|temp)_/ {
        deny all;
    }

    location ~ fileadmin/(?:templates)/.*\.(?:txt|ts|typoscript)$ {
        deny all;
    }

    location ~ ^(?:vendor|typo3_src|typo3temp/var) {
        deny all;
    }

    location ~ (?:typo3conf/ext|typo3/sysext|typo3/ext)/[^/]+/(?:Configuration|Resources/Private|Tests?|Documentation|docs?)/ {
        deny all;
    }

    location / {
        try_files \$uri \$uri/ /index.php\$is_args\$args;
    }

    location = /typo3 {
        rewrite ^ /typo3/;
    }

    location /typo3/ {
        absolute_redirect off;
        try_files \$uri /typo3/index.php\$is_args\$args;
    }

    location ~ [^/]\.php(/|$) {
        fastcgi_split_path_info ^(.+?\.php)(/.*)$;
        if (!-f \$document_root\$fastcgi_script_name) {
            return 404;
        }
	fastcgi_param HTTPS 'off';
        fastcgi_intercept_errors on;
        fastcgi_buffer_size 32k;
        fastcgi_buffers 16 16k;
        fastcgi_busy_buffers_size 128k;
        fastcgi_temp_file_write_size 128k;
        fastcgi_connect_timeout 240s;
        fastcgi_read_timeout 240s;
        fastcgi_send_timeout 240s;

        fastcgi_pass 127.0.0.1:9000;
        fastcgi_index index.php;
        include fastcgi.conf;
    }

    include default.d/*.conf;
}
EOF
