#!/bin/sh

#############
# nginx
#############

# define folder for additional configurations
if [ ! -d "/etc/nginx/default.d" ]; then
  mkdir -p -m 755 /etc/nginx/default.d
fi

cat >/etc/nginx/http.d/default.conf <<EOF
server {
    root ${APP_HOME};
    index index.php index.html index.htm;

    client_max_body_size  100M;

    access_log  /dev/stdout  main;

    #error_page   500 502 503 504  /50x.html;
    #location = /50x.html {
    #    root   /usr/share/nginx/html;
    #}

    location = /favicon.ico { log_not_found off; access_log off; }
    location = /robot.txt { log_not_found off; access_log off; }

    # Deny all attempts to access hidden files such as .htaccess, .htpasswd, .DS_Store (Mac).
    location ~ /\. {
       deny all;
       access_log off;
       log_not_found off;
    }

    location ~ \.php$ {
      try_files \$uri =404;
      include /etc/nginx/fastcgi_params;
      fastcgi_pass 127.0.0.1:9000;
      fastcgi_index index.php;
      fastcgi_split_path_info ^(.+\.php)(/.+)$;
      fastcgi_param SCRIPT_FILENAME \$document_root\$fastcgi_script_name;
      fastcgi_param HTTPS 'off';
      fastcgi_intercept_errors on;
      fastcgi_buffer_size 128k;
      fastcgi_buffers 256 16k;
      fastcgi_busy_buffers_size 256k;
      fastcgi_temp_file_write_size 256k;
      fastcgi_read_timeout 1200;
   }

   location ~ /\.(js|css)$ {
      expires 604800s;
   }

   if (!-e \$request_filename){
     rewrite ^/(.+)\.(\d+)\.(php|js|css|png|jpg|gif|gzip)$ /\$1.\$3 last;
   }

  location ~* ^/fileadmin/(.*/)?_recycler_/ {
    deny all;
  }

  location ~* ^/fileadmin/templates/.*(\.txt|\.ts)$ {
    deny all;
  }

  location ~* ^/typo3conf/ext/[^/]+/Resources/Private/ {
    deny all;
  }

  location ~* ^/(typo3/|fileadmin/|typo3conf/|typo3temp/|uploads/|favicon\.ico) {
  }

  location / {
    if (\$query_string ~ ".+") {
      return 405;
    }
    if (\$http_cookie ~ 'nc_staticfilecache|be_typo_user|fe_typo_user' ) {
      return 405;
    } # pass POST requests to PHP
    if (\$request_method !~ ^(GET|HEAD)$ ) {
      return 405;
    }
    if (\$http_pragma = 'no-cache') {
      return 405;
    }
    if (\$http_cache_control = 'no-cache') {
      return 405;
    }
    error_page 405 = @nocache;
    try_files /typo3temp/tx_ncstaticfilecache/\$host\${request_uri}index.html @nocache;
  }

  location @nocache {
    try_files \$uri \$uri/ /index.php\$is_args\$args;
  }

  include default.d/*.conf;
}
EOF
